dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.4
  permission_handler: ^11.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  intl: ^0.18.1
  animations: ^2.0.11
  fl_chart: ^0.68.0
  uuid: ^4.3.3
